spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  cache:
    type: simple

logging:
  level:
    root: INFO
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

  endpoint:
    health:
      show-details: always