version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: coworking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: coworking_db
      POSTGRES_USER: coworking_user
      POSTGRES_PASSWORD: coworking_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coworking_user -d coworking_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 👇 ESTE ES EL NUEVO SERVICIO
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: coworking-api

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/coworking_db
      DB_USERNAME: coworking_user
      DB_PASSWORD: coworking_password

    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: coworking-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@coworking.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: