spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/coworking_db
    username: coworking_user
    password: coworking_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never